### ISSUE TITLE
Provide the outputs in the `examples` directory?

### ISSUE THREAD

**Issue by guidolodetti** [ccarcaci/apispecmd-ts#2]
Hey Claudio! Great project 😃

Is it possible to also have the outputs in the `examples` directory? So we can quickly see the results without running a single line of code :)

Thanks!

Guido

**Comment by ccarcaci** [comment]
Hi Guido,
nice idea.
Here we go: https://github.com/ccarcaci/apispecmd-ts/tree/main/openapi/examples/output
;)

Thank you
